version: '1.0.{build}'
image: Previous Visual Studio 2019
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./PayFI.NET.sln --verbosity m
build_script:
  # output will be in ./src/bin/debug/netcoreapp1.1/publish
  - cmd: dotnet publish ./PayFI.NET/PayFI.NET.Library.csproj
after_build:
  # For once the build has completed
artifacts:
 - path: './PayFI.NET/bin/Debug/netstandard2.0/publish'
   name: PayFI.NET
   type: Library
clone_depth: 1
test_script:
  # restore packages for our unit tests
  - cmd: dotnet restore ./PayFI.Net.Tests/PayFI.Net.Tests.csproj --verbosity m
  # run the unit tests (requires changing into the test directory)
  - cmd: cd PayFI.Net.Tests
  - cmd: dotnet test
on_finish :
  # any cleanup in here
deploy: off